# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

import os
import sys

# Forza l'uso del path corrente
current_dir = os.getcwd()

a = Analysis(
    ['main.py'],
    pathex=[current_dir],
    hookspath=[current_dir],
    binaries=[
        ('venv/Lib/site-packages/sharpynt/config_data', 'sharpynt/config_data'),
    ],
    datas=[
        ('config/repo_update_default.json', 'config'),
        ('config/banks_default.json', 'config'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'sqlalchemy',
        'sqlalchemy.ext.baked',
        'sqlalchemy.sql.default_comparator',
        'sqlalchemy.ext.declarative',
        'pydantic',
        'pydantic.networks',
        'pydantic_settings',
        'pydantic_core',
        'pydantic.deprecated',
        'pydantic.deprecated.decorator',
        'pydantic.json_schema',
        'pydantic.annotated_handlers',
        'pydantic.functional_validators',
        'pydantic.functional_serializers',
        'passlib',
        'passlib.context',
        'passlib.handlers',
        'passlib.handlers.bcrypt',
        'passlib.hash',
        'jose',
        'jose.jwt',
        'jose.jws',
        'jose.jwe',
        'jose.backends',
        'jose.backends.cryptography_backend',
        'jose.constants',
        'python_multipart',
        'starlette',
        'fastapi',
        'requests',
        'pandas',
        'openpyxl',
        'bcrypt',
        'cryptography',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.backends',
        'cryptography.hazmat.backends.openssl',
        'email_validator',
        'db',
        'db.database',
        'db.models',
        'db.crud',
        'db.init_banks',
        'api',
        'api.auth',
        'api.users',
        'api.tasks',
        'api.audit',
        'api.flows',
        'core',
        'core.config',
        'core.config_setup',
        'core.security',
        'core.auditing',
        'scripts',
        'scripts.generate_flows_from_excel',
        'scripts.main',
        'scripts.data_factory',
        'scripts.utility',
        'numpy',
        'openpyxl',
        'fluentx',
        'fluentx.flow_executor',
        'fluentx.utility',
        'selenium',
        'selenium.webdriver',
        'selenium.webdriver.common',
        'selenium.webdriver.common.by',
        'selenium.webdriver.support',
        'selenium.webdriver.support.ui',
        'selenium.webdriver.support.expected_conditions',
        'selenium.common',
        'selenium.common.exceptions',
        'textual',
        'beautifulsoup4',
        'keyboard',
        'pyautogui',
        'pynput',
        'opencv-python',
        'sharpynt',
        'Office365-REST-Python-Client',
        'python-pptx',
        'lxml',
        'msal',
        'PyJWT',
        'psutil',
    ],
    hooksconfig={},
    runtime_hooks=['pyi_rth_database.py', 'pyi_rth_api_modules.py'],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='sdp-api',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)