# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('api/auth.py', 'api'),
        ('api/flows.py', 'api'),
        ('api/tasks.py', 'api'),
        ('api/reportistica.py', 'api'),
        ('api/repo_update.py', 'api'),
        ('api/settings_path.py', 'api'),
        ('api/banks.py', 'api'),
        ('core/config.py', 'core'),
        ('core/security.py', 'core'),
        ('scripts/generate_flows_from_excel.py', 'scripts'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'sqlalchemy',
        'sqlalchemy.ext.baked',
        'sqlalchemy.sql.default_comparator',
        'sqlalchemy.ext.declarative',
        'pydantic',
        'pydantic.networks',
        'pydantic_settings',
        'passlib',
        'passlib.context',
        'passlib.handlers',
        'passlib.handlers.bcrypt',
        'passlib.hash',
        'jose',
        'jose.jwt',
        'jose.jws',
        'jose.jwe',
        'jose.backends',
        'jose.backends.cryptography_backend',
        'jose.constants',
        'python_multipart',
        'starlette',
        'fastapi',
        'requests',
        'pandas',
        'openpyxl',
        'bcrypt',
        'cryptography',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.backends',
        'cryptography.hazmat.backends.openssl',
        'email_validator',
        'db',
        'db.database',
        'db.models',
        'db.schemas',
        'db.crud',
        'db.init_banks',
        'api',
        'api.auth',
        'api.users',
        'api.tasks',
        'api.audit',
        'api.flows',
        'core',
        'core.config',
        'core.security',
        'scripts',
        'scripts.generate_flows_from_excel',
        'numpy',
        'openpyxl',
    ],
    hooksconfig={},
    runtime_hooks=['pyi_rth_database.py', 'pyi_rth_api_modules.py'],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='sdp-api',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)